### ISSUE TITLE
track `Proposal` reference onchain

### ISSUE THREAD

**Issue by skaunov** [skaunov/puzzlers_voting_aleo#1]
I feel like it's possible that it could be better for [`mapping`](https://github.com/skaunov/puzzlers_voting_aleo/blob/094584d477f4f8087b3d5481cda23284463029d4/src/main.leo#L3) to hold reference to that rolling `record` with current voting state. 

The main [question is what's the best data to reference](https://discord.com/channels/700454073459015690/745897257160933516/1140903451530899497).

_As a  follow-up an analysis of fee impact for `mapping` update would be nice._

**Comment by yono77** [comment]
ask

**Comment by skaunov** [comment]
The idea wasn't indeed that good.
https://discord.com/channels/700454073459015690/745897257160933516/1141872306646433863
